// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musing.Edu.Hostel.DataBase;

namespace Musing.Edu.Hostel.DataBase.Migrations
{
    [DbContext(typeof(HostelDbContext))]
    partial class HostelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ChargeOccurencePeriod")
                        .HasColumnType("int");

                    b.Property<int>("ChargeOccurencePeriodType")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuildingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MHostelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MHostelId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("FloorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.HostelAndWardenRelations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HostelId")
                        .HasColumnType("int");

                    b.Property<int?>("MHostelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WardenAssignedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WardenAssignedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WardenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MHostelId");

                    b.HasIndex("WardenId");

                    b.ToTable("HostelAndWardenRelations");
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.MHostel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllowedGender")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hostels");
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Warden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wardens");
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Bed", b =>
                {
                    b.HasOne("Musing.Edu.Hostel.Domain.Room", null)
                        .WithMany("BedCollection")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Building", b =>
                {
                    b.HasOne("Musing.Edu.Hostel.Domain.MHostel", null)
                        .WithMany("BuildingCollection")
                        .HasForeignKey("MHostelId");
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Floor", b =>
                {
                    b.HasOne("Musing.Edu.Hostel.Domain.Building", null)
                        .WithMany("FloorCollection")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.HostelAndWardenRelations", b =>
                {
                    b.HasOne("Musing.Edu.Hostel.Domain.MHostel", null)
                        .WithMany("HostelAndWarden")
                        .HasForeignKey("MHostelId");

                    b.HasOne("Musing.Edu.Hostel.Domain.Warden", null)
                        .WithMany("WardenAndHostelRelations")
                        .HasForeignKey("WardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.MHostel", b =>
                {
                    b.OwnsOne("Musing.Edu.Hostel.Domain.HostelGeneralInformation", "GeneralInformation", b1 =>
                        {
                            b1.Property<int>("MHostelId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ContactNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("MailId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Pin")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MHostelId");

                            b1.ToTable("Hostels");

                            b1.WithOwner()
                                .HasForeignKey("MHostelId");
                        });
                });

            modelBuilder.Entity("Musing.Edu.Hostel.Domain.Room", b =>
                {
                    b.HasOne("Musing.Edu.Hostel.Domain.Floor", null)
                        .WithMany("RoomCollection")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
